<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\..\..\res\sdk_templates\client\csharp\HeartbeatState.cs" Link="HeartbeatState.cs" />
    <Compile Include="..\..\..\..\res\sdk_templates\client\csharp\NetworkLifecycleState.cs" Link="NetworkLifecycleState.cs" />
  </ItemGroup>
</Project>
