LIB =	navigation

SRCS =						\
	navigation				\
	navigation_handle		\
	navigation_tile_handle	\
	navigation_mesh_handle

ifndef KBE_ROOT
export KBE_ROOT := $(subst /kbe/src/lib/$(LIB),,$(CURDIR))
endif

include $(KBE_ROOT)/kbe/src/build/common.mak
