if(NOT DEFINED KBE_TRIPLET_ROOT OR NOT IS_DIRECTORY "${KBE_TRIPLET_ROOT}")
    message(FATAL_ERROR "KBE_TRIPLET_ROOT must contain the project overlay triplets")
endif()

function(kbe_assert_triplet triplet expected_architecture expected_system expected_osx_architecture)
    set(_kbe_triplet_file "${KBE_TRIPLET_ROOT}/${triplet}.cmake")
    if(NOT EXISTS "${_kbe_triplet_file}")
        message(FATAL_ERROR "Overlay triplet does not exist: ${_kbe_triplet_file}")
    endif()

    # 普通依赖继续静态链接；在函数作用域内加载可防止各用例的 port 状态相互污染。
    # Ordinary dependencies remain static; function scope prevents one port case from contaminating another.
    set(PORT fmt)
    unset(VCPKG_BUILD_TYPE)
    include("${_kbe_triplet_file}")
    if(NOT VCPKG_LIBRARY_LINKAGE STREQUAL "static")
        message(FATAL_ERROR "${triplet} must keep non-Python ports static")
    endif()
    if(DEFINED VCPKG_BUILD_TYPE)
        message(FATAL_ERROR "${triplet} must not force a build type for non-Python ports")
    endif()
    if(NOT VCPKG_CRT_LINKAGE STREQUAL "dynamic")
        message(FATAL_ERROR "${triplet} must use the dynamic CRT")
    endif()
    if(NOT VCPKG_TARGET_ARCHITECTURE STREQUAL expected_architecture)
        message(FATAL_ERROR "${triplet} architecture mismatch: ${VCPKG_TARGET_ARCHITECTURE}")
    endif()
    if(expected_system AND NOT VCPKG_CMAKE_SYSTEM_NAME STREQUAL expected_system)
        message(FATAL_ERROR "${triplet} system mismatch: ${VCPKG_CMAKE_SYSTEM_NAME}")
    endif()
    if(expected_osx_architecture AND
       NOT VCPKG_OSX_ARCHITECTURES STREQUAL expected_osx_architecture)
        message(FATAL_ERROR "${triplet} macOS architecture mismatch: ${VCPKG_OSX_ARCHITECTURES}")
    endif()

    set(PORT python3)
    unset(VCPKG_BUILD_TYPE)
    include("${_kbe_triplet_file}")
    if(NOT VCPKG_LIBRARY_LINKAGE STREQUAL "dynamic")
        message(FATAL_ERROR "${triplet} must build python3 dynamically")
    endif()
    if(NOT VCPKG_BUILD_TYPE STREQUAL "release")
        message(FATAL_ERROR "${triplet} must build python3 as Release only")
    endif()
endfunction()

kbe_assert_triplet("x64-windows-static-md" x64 "" "")
kbe_assert_triplet("arm64-windows-static-md" arm64 "" "")
kbe_assert_triplet("x64-linux" x64 Linux "")
kbe_assert_triplet("arm64-linux" arm64 Linux "")
kbe_assert_triplet("x64-osx" x64 Darwin x86_64)
kbe_assert_triplet("arm64-osx" arm64 Darwin arm64)

message(STATUS "Verified static dependencies and dynamic Release Python for all overlay triplets")
